"""
advisor/llm/client.py — PART 8: provider-agnostic CLOUD LLM client.

One `generate(system, prompt) -> str` interface, three cloud adapters selected by
config (`ADVISOR_LLM_PROVIDER`): **groq** (default, hosts Gemma `gemma2-9b-it`),
**anthropic**, **gemini**. No local models / Ollama.

A deterministic **mock** provider is the automatic fallback when no API key /
SDK is present, so every downstream module (reasoner, validation, ranking, API)
is testable offline. The mock is clearly flagged via `.is_mock`.
"""
from __future__ import annotations

import json
from functools import lru_cache

from advisor.config import CONFIG


class LLMClient:
    is_mock = False
    provider = "base"

    def generate(self, system: str, prompt: str) -> str:
        raise NotImplementedError


class GroqClient(LLMClient):
    provider = "groq"

    def __init__(self, config=CONFIG):
        from langchain_groq import ChatGroq
        self.cfg = config
        self.llm = ChatGroq(model=config.llm_model, temperature=config.llm_temperature,
                            max_tokens=config.llm_max_tokens, api_key=config.groq_api_key)

    def generate(self, system: str, prompt: str) -> str:
        msg = self.llm.invoke([("system", system), ("human", prompt)])
        return msg.content


class AnthropicClient(LLMClient):
    provider = "anthropic"

    def __init__(self, config=CONFIG):
        import anthropic
        self.cfg = config
        self.client = anthropic.Anthropic(api_key=config.anthropic_api_key)
        self.model = config.llm_model if "claude" in config.llm_model else "claude-sonnet-5"

    def generate(self, system: str, prompt: str) -> str:
        r = self.client.messages.create(
            model=self.model, max_tokens=self.cfg.llm_max_tokens,
            temperature=self.cfg.llm_temperature, system=system,
            messages=[{"role": "user", "content": prompt}])
        return "".join(b.text for b in r.content if getattr(b, "type", "") == "text")


class GeminiClient(LLMClient):
    provider = "gemini"

    def __init__(self, config=CONFIG):
        import google.generativeai as genai
        genai.configure(api_key=config.gemini_api_key)
        self.cfg = config
        self.model = genai.GenerativeModel(
            config.llm_model if "gemini" in config.llm_model else "gemini-1.5-flash")

    def generate(self, system: str, prompt: str) -> str:
        r = self.model.generate_content(f"{system}\n\n{prompt}")
        return r.text


class MockClient(LLMClient):
    """Deterministic, grounded-by-construction reasoner. It does NOT invent facts:
    it assembles interventions from the knowledge graph and cites the retrieved
    chunks it is given, so the pipeline is fully runnable without an API key."""
    is_mock = True
    provider = "mock"

    def generate(self, system: str, prompt: str) -> str:
        payload = _parse_mock_payload(prompt)
        return json.dumps(_mock_reason(payload), indent=2)


def _parse_mock_payload(prompt: str) -> dict:
    try:
        start = prompt.index("<<<CONTEXT_JSON>>>") + len("<<<CONTEXT_JSON>>>")
        end = prompt.index("<<<END_CONTEXT_JSON>>>")
        return json.loads(prompt[start:end].strip())
    except Exception:
        return {}


def _mock_reason(payload: dict) -> dict:
    from advisor.kg.knowledge_graph import get_knowledge_graph
    from advisor.config import ACTION_TARGET_SOURCE, ACTION_CATALOGUE
    ctx = payload.get("context", {})
    stage = ctx.get("grap_stage") or "Stage I"
    sources = list((ctx.get("dominant_sources") or {}).keys())
    src_map = {"industry": "industrial"}
    sources = [src_map.get(s, s) for s in sources]
    cites = payload.get("citations", [])
    kg = get_knowledge_graph()

    interventions = []
    seen = set()
    for src in sources or ["dust"]:
        for act in kg.interventions_for_source(src, stage):
            if act in seen:
                continue
            seen.add(act)
            meta = ACTION_CATALOGUE.get(act, {})
            interventions.append({
                "action": act,
                "title": meta.get("label", act),
                "target_source": ACTION_TARGET_SOURCE.get(act, src),
                "rationale": f"{src} is a dominant source at {stage}; this measure is "
                             f"prescribed under GRAP {stage}.",
                "citations": [c.get("citation", c.get("title", "")) for c in cites[:2]],
                "confidence": 0.7,
            })
    return {
        "aqi_assessment": f"Predicted AQI {ctx.get('predicted_aqi')} "
                          f"({ctx.get('aqi_band')}), GRAP {stage}.",
        "source_analysis": f"Dominant sources: {', '.join(sources) or 'n/a'}.",
        "policy_basis": [c.get("citation", c.get("title", "")) for c in cites[:3]],
        "interventions": interventions,
        "note": "Generated by deterministic offline reasoner (no LLM key configured).",
    }


_REGISTRY = {"groq": GroqClient, "anthropic": AnthropicClient,
             "gemini": GeminiClient, "mock": MockClient}


def make_llm_client(config=CONFIG) -> LLMClient:
    provider = config.llm_provider
    key = {"groq": config.groq_api_key, "anthropic": config.anthropic_api_key,
           "gemini": config.gemini_api_key, "mock": "x"}.get(provider, "")
    if provider != "mock" and not key:
        print(f"[llm] no API key for '{provider}' -> using deterministic mock. "
              f"Set the key in .env to enable real reasoning.")
        return MockClient()
    try:
        return _REGISTRY.get(provider, MockClient)(config)
    except Exception as e:
        print(f"[llm] provider '{provider}' failed to init ({e}) -> mock.")
        return MockClient()


@lru_cache(maxsize=1)
def get_llm_client() -> LLMClient:
    return make_llm_client()


if __name__ == "__main__":
    c = get_llm_client()
    print("provider:", c.provider, "| mock:", c.is_mock)
    payload = {"context": {"predicted_aqi": 312, "aqi_band": "Very Poor",
                           "grap_stage": "Stage II", "dominant_sources": {"traffic": 0.4, "dust": 0.3}},
               "citations": [{"citation": "GRAP Stage II — CAQM — 2022-08-05", "title": "GRAP Stage II"}]}
    prompt = f"<<<CONTEXT_JSON>>>{json.dumps(payload)}<<<END_CONTEXT_JSON>>>"
    print(c.generate("You are an air-quality policy advisor.", prompt)[:600])
